var user = {
login: "franklinfinger",
id: 10949845,
avatar_url: "https://avatars.githubusercontent.com/u/10949845?v=3",
gravatar_id: "",
url: "https://api.github.com/users/franklinfinger",
html_url: "https://github.com/franklinfinger",
followers_url: "https://api.github.com/users/franklinfinger/followers",
following_url: "https://api.github.com/users/franklinfinger/following{/other_user}",
gists_url: "https://api.github.com/users/franklinfinger/gists{/gist_id}",
starred_url: "https://api.github.com/users/franklinfinger/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/franklinfinger/subscriptions",
organizations_url: "https://api.github.com/users/franklinfinger/orgs",
repos_url: "https://api.github.com/users/franklinfinger/repos",
events_url: "https://api.github.com/users/franklinfinger/events{/privacy}",
received_events_url: "https://api.github.com/users/franklinfinger/received_events",
type: "User",
site_admin: false,
name: "Frank Finger",
company: null,
blog: null,
location: null,
email: "franklinfinger@gmail.com",
hireable: null,
bio: null,
public_repos: 22,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2015-02-10T23:35:56Z",
updated_at: "2016-02-02T21:31:24Z"
}
